version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bling_products
    ports:
      - "5432:5432"
